foreground              #f8f8f2
background              #282a36
selection_foreground    #282a36
selection_background    #bd93f9

cursor                  #f8f8f2
cursor_text_color       #282a36

url_color               #8be9fd

active_border_color     #bd93f9
inactive_border_color   #44475a
bell_border_color       #ff5555

active_tab_foreground   #282a36
active_tab_background   #bd93f9
inactive_tab_foreground #f8f8f2
inactive_tab_background #44475a
tab_bar_background      #282a36

color0  #44475a
color8  #6272a4
color1  #ff5555
color9  #ff6e6e
color2  #50fa7b
color10 #69ff94
color3  #f1fa8c
color11 #ffffa5
color4  #6272a4
color12 #8be9fd
color5  #bd93f9
color13 #ff79c6
color6  #bd93f9
color14 #a4ffff
color7  #f8f8f2
color15 #ffffff
