# Emerald

foreground              #d8f3dc
background              #0b1d16
selection_foreground    #0b1d16
selection_background    #52b788

cursor                  #d8f3dc
cursor_text_color       #0b1d16

url_color               #74c69d

active_border_color     #52b788
inactive_border_color   #2d6a4f
bell_border_color       #ef476f

active_tab_foreground   #0b1d16
active_tab_background   #52b788
inactive_tab_foreground #d8f3dc
inactive_tab_background #143d2f
tab_bar_background      #0b1d16

color0  #143d2f
color8  #2d6a4f

color1  #d62839
color9  #ef476f

color2  #52b788
color10 #74c69d

color3  #ffd166
color11 #f4d35e

color4  #40916c
color12 #95d5b2

color5  #2ec4b6
color13 #6ee7b7

color6  #1b9aaa
color14 #52b788

color7  #b7e4c7
color15 #d8f3dc
