foreground              #dcd7ba
background              #1f1f28
selection_foreground    #1f1f28
selection_background    #7e9cd8

cursor                  #dcd7ba
cursor_text_color       #1f1f28

url_color               #7fb4ca

active_border_color     #7e9cd8
inactive_border_color   #54546d
bell_border_color       #c34043

active_tab_foreground   #1f1f28
active_tab_background   #7e9cd8
inactive_tab_foreground #dcd7ba
inactive_tab_background #2a2a37
tab_bar_background      #1f1f28

color0  #2a2a37
color8  #54546d
color1  #c34043
color9  #e82424
color2  #98bb6c
color10 #76946a
color3  #c0a36e
color11 #e6c384
color4  #7e9cd8
color12 #7fb4ca
color5  #957fb8
color13 #938aa9
color6  #727169
color14 #98bb6c
color7  #c8c093
color15 #dcd7ba
