# Basic colors
foreground              #ecdfe5
background              #171216
selection_foreground    #f7daee
selection_background    #554150

# Cursor colors
cursor                  #f2b3e6
cursor_text_color       #4c1f48

# URL underline color when hovering with mouse
url_color               #f5b8a6

# Kitty window border colors
active_border_color     #f2b3e6
inactive_border_color   #4e444b
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #ffd7f4
active_tab_background   #663560
inactive_tab_foreground #d1c2cb
inactive_tab_background #241e22
tab_bar_background      #171216

# Colors for marks
mark1_foreground #4c1f48
mark1_background #f2b3e6
mark2_foreground #3d2b3a
mark2_background #dabfd2
mark3_foreground #4c261a
mark3_background #f5b8a6

# The 16 terminal colors
# black
color0 #4e444b
color8 #9a8d95

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #f2b3e6
color10 #ffd7f4

# yellow
color3  #f5b8a6
color11 #ffdbd0

# blue
color4  #dabfd2
color12 #f7daee

# magenta
color5  #663560
color13 #804d79

# cyan
color6  #554150
color14 #663c2f

# white
color7  #d1c2cb
color15 #ecdfe5
