emojiPicker = "alacritty --class unipicker -e unipicker --copy-command 'wl-copy -t text/plain'"
discord     = "discord"
terminal    = "kitty"
fileManager = "dolphin"
menu        = "rofi -show drun -show-icons -theme '/home/azeturk810/.config/rofi/rofi_themes/appmnu.rasi' -icon-theme '/home/azeturk810/.config/rofi/rofi_themes/slate.rasi' -hover-select -me-select-entry '' -me-accept-entry MousePrimary"
browser     = "firefox"
zen         = "app.zen_browser.zen"
scripts     = "~/.config/scripts/"
